apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-secret
type: Opaque
stringData:
    RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rabbitmq
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
                - name: rabbitmq
                  image: xcomponent/docker-analysis:rabbitmq-ubi-fixuirabbit-ac065937f3aa7bdfe7e1a8e60b4c59e41f6783f8
                  env:
                      - name: HOME
                        value: /var/lib/rabbitmq
                      - name: RABBITMQ_DEFAULT_USER
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq-secret
                                key: RABBITMQ_DEFAULT_USER
                      - name: RABBITMQ_DEFAULT_PASS
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq-secret
                                key: RABBITMQ_DEFAULT_PASS
                  ports:
                      - containerPort: 5672 # AMQP
                      - containerPort: 15672 # Web UI
                  volumeMounts:
                      - mountPath: /var/lib/rabbitmq
                        name: rabbitmq-data
            volumes:
                - name: rabbitmq-data
                  emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
spec:
    selector:
        app: rabbitmq
    ports:
        - name: amqp
          port: 5672
          targetPort: 5672
        - name: http
          port: 15672
          targetPort: 15672
    type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: rabbitmq
spec:
    to:
        kind: Service
        name: rabbitmq
    port:
        targetPort: http
    tls:
        termination: edge
