x4bSpecificDnszone: x4b.MY_APPCONTROL_DOMAIN # DNS name to be associated to the login service
authentication:
    secretName: MY_SECRET_NAME # Name of the k8s secret holding the private and public keys used to sign and validate
    refreshTokenDurationInHours: 10080 # Duration of refresh tokens generated for users in hours. (default 12)
    accessTokenDurationInMinutes: 21 # Duration of access tokens generated for users in minutes. (default 5)
    localUsersEnabled: true # Enable authentication using local users. (default true)
    ldapEnabled: false # Enable ldap. (default false) If you want to enable Ldap you have to disable the local users (localUsersEnabled: false)
    ldapUseSsl: false # Use ssl on Ldap. (default false)
    ldapServer: # Ldap server
    ldapPort: # Ldap port (default 389 or 636 if ldapUseSsl is true)
    ldapSearchBase: # Ldap search base for users
    ldapSearchAttribute: # Ldap search attribute (default userPrincipalName)
sql:
    connectionString: 'YOUR_SQLSERVER_CONNECTION_STRING'
ingress:
    class: nginx # If you use an nginx ingress controller
    tls: true # Only if you want to use ssl with a cluster issuer
