site_name: AppControl
docs_dir: '../../docs/en' # Where to find the English markdown files
site_dir: '../../site/en' # Where to put the English HTML files
site_url: https://xcomponent.github.io/
repo_url: https://xcomponent.github.io/appcontrol-documentation/

nav:
    - Introduction: index.md
    - Getting Started:
          - Introduction to AppControl SaaS: gettingStarted
          - Demo setup with no connection to local infrastructure: gettingStarted/#try-demo
          - Connecting local infrastructure: gettingStarted/#connecting-to-local-infrastructure
    - Core Concepts: coreconcepts.md
    - Create your own application manually:
          - Introduction: map
          - YAML Format: map#yaml-format
          - XML Format: map#xml-format
          - Built-in wizards: map#built-in-wizards
          - Enrich your application with dynamic informations: dynamicmapinformations
    - Create your own application using wizard:
          - Auto-Generate Application from Running Processes: map/#auto-generate-application-from-running-processes
          - Auto-Generate Application from Azure Tenant: map/#auto-generate-application-from-azure-tenant
    - Gateways and Agents Installation in Local Infrastructure:
          - Introduction: x4bcli
          - Quick installation: x4bcli#quick-deployment-of-agents-and-gateways-windows-and-macos
          - Gateway installation: x4bcli/#x4b-gateway-custom-installation
          - Agent installation: agents
    - Gateways and Agents Installation in Azure: agentazure
    - Git integration: repo
    - Advanced:
          - Install standalone: standalone
          - AppControl Cli: cli.md
          - How to import your Centreon setup into AppControl: centreon.md
          - How to integrate AppControl with a ServiceNow Cmdb: cmdb.md

theme:
    name: material
    logo: logo2.svg
    repo: 'github'
    language: en
    repo_url: 'https://github.com/xcomponent/appcontrol-documentation'
    palette:
        primary: 'green' # Change this to any supported color
        accent: '#532699' # Secondary color
    toggle:
        icon: material/toggle-switch
        name: Toggle dark mode
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.instant.preview
        - navigation.tracking
        - tabs # Enable tabs for navigation
        - navigation.expand # Automatically expand navigation sections

markdown_extensions:
    - attr_list

extra:
    alternate:
        - name: English
          link: /en/
          lang: en
        - name: French
          link: /fr/
          lang: fr

plugins:
    - search:
          lang: en
